version: '3.5'

services:
    briefing-front:
        container_name: briefing_front
        build:
            context: .
        restart: always
        ports:
            - "80:80"
        env_file:
            - .env