name: Rodar testes ao alterar versão

on:
  push:
    paths:
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Verificando repositório
        uses: actions/checkout@v2

      - name: Recuperando versão anterior
        id: get_previous_version
        #script para recuperação de versão anterior baseada no último commit
        run: echo "::set-output name=previous_version::$(git show HEAD~1:package.json | jq -r .version)"

      - name: Get Current Version
        id: get_current_version
        #script para recuperação de versão atual
        run: echo "::set-output name=current_version::$(jq -r .version package.json)"

      - name: Compare Versions
        id: compare_versions
        #Comparação entre versões, se não houver mudanças, pula o processo todo
        run: |
          if [ "${{ steps.get_previous_version.outputs.previous_version }}" != "${{ steps.get_current_version.outputs.current_version }}" ]; then
            echo "Mudança nas versões"
            exit 0
          else
            echo "Não houve mudança de versões"
            exit 1
          fi

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando dependências e pacotes do Node
        run: npm install

      - name: Rodando testes
        if: ${{ success() }}
        run: npm test